# Generated by Django 3.2.dev20201203083208 on 2021-08-15 17:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAgen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('no_hp', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('alamat', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('berat', models.DecimalField(decimal_places=4, max_digits=7)),
                ('harga', models.DecimalField(decimal_places=3, max_digits=10)),
                ('jenis_packing', models.CharField(default='dus/box', max_length=20)),
                ('dari', models.CharField(max_length=20)),
                ('tujuan', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('no_body', models.CharField(max_length=7, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Konsumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('no_hp', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('alamat', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('no_hp', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cargo.bus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registrasi_Barang_Budiman_Cargo',
            fields=[
                ('no_reg', models.IntegerField(primary_key=True, serialize=False)),
                ('barang', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='cargo.barang')),
                ('penerima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konsumenPenerima', to='cargo.konsumen')),
                ('pengirim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konsumenPengirim', to='cargo.konsumen')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('kemampuan', models.CharField(default=models.CharField(max_length=20), max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tanda_Terima_Budiman_Cargo',
            fields=[
                ('no_seri', models.IntegerField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('agen_penerima', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='agenPenerima', to='cargo.adminagen')),
                ('agen_pengirim', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='agenPengirim', to='cargo.adminagen')),
                ('registrasi', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='cargo.registrasi_barang_budiman_cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi_Harian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.personil')),
                ('tanda_terima', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='cargo.tanda_terima_budiman_cargo')),
            ],
        ),
        migrations.AddField(
            model_name='personil',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.role'),
        ),
        migrations.AddField(
            model_name='konsumen',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.role'),
        ),
        migrations.AddField(
            model_name='adminagen',
            name='agen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.agen'),
        ),
        migrations.AddField(
            model_name='adminagen',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.role'),
        ),
    ]
