# Generated by Django 3.2.dev20201203083208 on 2021-08-16 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('no_hp', models.CharField(max_length=15)),
                ('paraf', models.TextField()),
                ('agen', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cargo.agen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.role')),
            ],
        ),
        migrations.RemoveField(
            model_name='registrasi_barang_budiman_cargo',
            name='barang',
        ),
        migrations.RemoveField(
            model_name='registrasi_barang_budiman_cargo',
            name='penerima',
        ),
        migrations.RemoveField(
            model_name='registrasi_barang_budiman_cargo',
            name='pengirim',
        ),
        migrations.RemoveField(
            model_name='tanda_terima_budiman_cargo',
            name='agen_penerima',
        ),
        migrations.RemoveField(
            model_name='tanda_terima_budiman_cargo',
            name='agen_pengirim',
        ),
        migrations.RemoveField(
            model_name='tanda_terima_budiman_cargo',
            name='registrasi',
        ),
        migrations.RemoveField(
            model_name='transaksi_harian',
            name='personil',
        ),
        migrations.RemoveField(
            model_name='transaksi_harian',
            name='tanda_terima',
        ),
        migrations.RemoveField(
            model_name='konsumen',
            name='password',
        ),
        migrations.RemoveField(
            model_name='konsumen',
            name='role',
        ),
        migrations.RemoveField(
            model_name='konsumen',
            name='status',
        ),
        migrations.RemoveField(
            model_name='konsumen',
            name='username',
        ),
        migrations.RemoveField(
            model_name='personil',
            name='password',
        ),
        migrations.RemoveField(
            model_name='personil',
            name='role',
        ),
        migrations.RemoveField(
            model_name='personil',
            name='status',
        ),
        migrations.RemoveField(
            model_name='personil',
            name='username',
        ),
        migrations.DeleteModel(
            name='AdminAgen',
        ),
        migrations.DeleteModel(
            name='Registrasi_Barang_Budiman_Cargo',
        ),
        migrations.DeleteModel(
            name='Tanda_Terima_Budiman_Cargo',
        ),
        migrations.DeleteModel(
            name='Transaksi_Harian',
        ),
        migrations.AddField(
            model_name='admin',
            name='akun',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='cargo.akun'),
        ),
        migrations.AddField(
            model_name='konsumen',
            name='akun',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='cargo.akun'),
        ),
        migrations.AddField(
            model_name='personil',
            name='akun',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='cargo.akun'),
        ),
    ]
